### PR TITLE
Added default value for SSM lookup

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**

### CODE REVIEW

**Comment by ozbillwang** [comment]
Thanks, @AndrewChubatiuk 

Please ignore the `Travis CI Build failed` error.

For this PR, do you mean to provide a default value if the SSM key is not exist or not found (for example, search in wrong region) . I think it should be handled by ansible conditions.

**Comment by AndrewChubatiuk** [comment]
Ansible conditions can be used when trying to get a single value from a SSM store. But there should be at least two tasks: first one is a lookup with `ignore_errors: True` and the second one with `when: result|failed`.
But it doesn't work for ansible templates, when there's a need to get multiple values from SSM store

**Comment by ozbillwang** [comment]
@AndrewChubatiuk 

I am thinking your PR recently and not confident for the change. 

What I suggest, currently this module (library/lookup) is still waiting to be merged into the main stream via https://github.com/ansible/ansible/pull/23460, so I prefer to get that PR to be merged first. 

Then we can discuss your PR, or you can raise PR directly to Ansible repo.  What do you think about this idea?

**Comment by ozbillwang** [comment]
@AndrewChubatiuk 

PR (https://github.com/ansible/ansible/pull/23460) has been merged. 

Are you fine to raise PR against ansible directly?

**Comment by ozbillwang** [comment]
no update, closed.

**Pull request closed without merging**
