### PR TITLE
Allow to request values by path and recursively

### PR DESCRIPTION
**Pull request by mtb-xt**
Hello.

I've tried to add the option to use boto's 'get_parameters_by_path' call.

Could you look at my implementation and say if you're willing to accept it, or you have some other approach in mind?

What I did, is added a check if there's a parameter called 'bypath', and if it is present, the lookup thing uses get_parameters_by_path. You can also specify 'recursive=true' in the parameters.

Example of use:
```
           - debug: msg="{{ lookup('ssm', '/UAT', 'region=ap-southeast-2', 'bypath' ) }}"
  
           - name: Parameters can be provided after the key be more specific about what to retrieve
             debug: msg='key contains {{item}}'
             with_ssm:
               - '/UAT'
               - 'region=ap-southeast-2'
               - 'bypath'
  
           - debug: msg="{{ lookup('ssm', '/UAT', 'region=ap-southeast-2', 'bypath', 'recursive=true' ) }}"
  
           - name: Parameters can be provided after the key be more specific about what to retrieve
             debug: msg='key contains {{item}}'
             with_ssm:
               - '/UAT'
               - 'region=ap-southeast-2'
               - 'bypath'
               - 'recursive=true'
```

This change was requested in your PR to ansible. 
P.S. I do not agree with them that you should use 'variables' to get the region.

### CODE REVIEW

**Comment by mtb-xt** [comment]
@ozbillwang  would you be able to look at this? Tests are failing because there are no credentials configured, but the code works for me

**Comment by ozbillwang** [comment]
@mtb-xt 

I did the change to use 'variables' to get the region because that's the request from ansible reviewers. 

I have adapted the commit about pylint error manually and updated to PR directly, which works fine. 👍 

Then I look into your code about `request values by path and recursively`. 

Several discussions already for this feature.

In https://github.com/ansible/ansible/pull/23460#issuecomment-322371751

>It seems like the only real change as far as API/CLI go is the `get-parameters-by-path` function. The create/update functions seem to be the same, just adding a / creates a path.

>@ozbillwang Do you think this is something you can look into adding. I can try to help, but don't have a lot of spare time at the moment.

and https://github.com/BWITS/ssm_parameter_store/pull/8

Personally i am fine to add this feature, but not sure ansible reviewer's option. Because from my experience, I can't add feature directly with my own way, when add a new feature, I need to confirm with them first. 

Reviewer @willthames has approved my changes. I am waiting to get that PR to be merged first. 

If we add new feature now, it need be reviewed again. So can we hold this PR currently?

**Comment by mtb-xt** [comment]
Sure, let's merge this to ansible as it is, I can reopen my PR against ansible directly. Thanks

**Comment by ozbillwang** [comment]
@mtb-xt 

The PR ( https://github.com/ansible/ansible/pull/23460) has been merged. 

You can raise a new PR directly to ansible and add your feature now.

**Pull request closed without merging**
